name: Build accessors

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.56
  
    - uses: actions/checkout@v4

    - name: Configure 
      run: emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: 1
        token : ${{ secrets.RELEASE_TOKEN }}
        files: build/theora_1.wasm

